runtime: java21
instance_class: F1
entrypoint: 'java -jar AI4MediaServer-all.jar'

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: .*
  script: auto
  secure: always
    
service: backend

automatic_scaling:
  max_instances: 2

env_variables:
  # App Engine automatically sets GOOGLE_CLOUD_PROJECT
  # Define your production URL here:
  APPENGINE_BASE_URL: "https://planner.catharsis.computer" 
  